// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhgkbO_lu_OMuO7W22wA82Zk9EoeWBSNU',
    appId: '1:154054396010:web:c160aea8f82f302a5fe213',
    messagingSenderId: '154054396010',
    projectId: 'schoolbridge-7ade3',
    authDomain: 'schoolbridge-7ade3.firebaseapp.com',
    storageBucket: 'schoolbridge-7ade3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzmssMMqe0QxNmqji3IIoj2L6oLMva15w',
    appId: '1:154054396010:android:11f75d2a3ea5a3fd5fe213',
    messagingSenderId: '154054396010',
    projectId: 'schoolbridge-7ade3',
    storageBucket: 'schoolbridge-7ade3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkTLgEc_qi6OdK9stODnGCgDKMiWrW1C4',
    appId: '1:154054396010:ios:b6810031840e3a4a5fe213',
    messagingSenderId: '154054396010',
    projectId: 'schoolbridge-7ade3',
    storageBucket: 'schoolbridge-7ade3.firebasestorage.app',
    iosBundleId: 'com.example.schoolbridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkTLgEc_qi6OdK9stODnGCgDKMiWrW1C4',
    appId: '1:154054396010:ios:b6810031840e3a4a5fe213',
    messagingSenderId: '154054396010',
    projectId: 'schoolbridge-7ade3',
    storageBucket: 'schoolbridge-7ade3.firebasestorage.app',
    iosBundleId: 'com.example.schoolbridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhgkbO_lu_OMuO7W22wA82Zk9EoeWBSNU',
    appId: '1:154054396010:web:0346c447023c160a5fe213',
    messagingSenderId: '154054396010',
    projectId: 'schoolbridge-7ade3',
    authDomain: 'schoolbridge-7ade3.firebaseapp.com',
    storageBucket: 'schoolbridge-7ade3.firebasestorage.app',
  );
}
